// FOR REDUX

// ------Registration
export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAILURE = 'GET_REGISTER_FAILURE';

// ------Login
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

// ------Logout
export const POST_LOG_OUT_REQUEST = 'POST_LOG_OUT_REQUEST';
export const GET_LOG_OUT_SUCCESS = 'GET_LOG_OUT_SUCCESS';
export const GET_LOG_OUT_FAILURE = 'GET_LOG_OUT_FAILURE';

// ------Login authentication
export const POST_USER_AUTH_REQUEST = 'POST_USER_AUTH_REQUEST';
export const GET_USER_AUTH_SUCCESS = 'GET_USER_AUTH_SUCCESS';
export const GET_USER_AUTH_FAILURE = 'GET_USER_AUTH_FAILURE';

// ------User Profile
export const POST_USER_PROFILE_BY_ID_REQUEST = 'POST_USER_PROFILE_BY_ID_REQUEST';
export const GET_USER_PROFILE_BY_ID_SUCCESS = 'GET_USER_PROFILE_BY_ID_SUCCESS';
export const GET_USER_PROFILE_BY_ID_FAILURE = 'GET_USER_PROFILE_BY_ID_FAILURE';


// ------Other User Profile
export const POST_OTHER_USER_PROFILE_BY_ID_REQUEST = 'POST_OTHER_USER_PROFILE_BY_ID_REQUEST';
export const GET_OTHER_USER_PROFILE_BY_ID_SUCCESS = 'GET_OTHER_USER_PROFILE_BY_ID_SUCCESS';
export const GET_OTHER_USER_PROFILE_BY_ID_FAILURE = 'GET_OTHER_USER_PROFILE_BY_ID_FAILURE';


//---------User Update Profile or cover Image
export const POST_UPDATE_PROFILE_IMAGE_REQUEST = 'POST_UPDATE_PROFILE_IMAGE_REQUEST';
export const GET_UPDATE_PROFILE_IMAGE_SUCCESS = 'GET_UPDATE_PROFILE_IMAGE_SUCCESS';
export const GET_UPDATE_PROFILE_IMAGE_FAILURE = 'GET_UPDATE_PROFILE_IMAGE_FAILURE';

// ------Forgot Password
export const POST_FORGET_PASSWORD_REQUEST = 'POST_FORGET_PASSWORD_REQUEST';
export const GET_FORGET_PASSWORD_SUCCESS = 'GET_FORGET_PASSWORD_SUCCESS';
export const GET_FORGET_PASSWORD_FAILURE = 'GET_FORGET_PASSWORD_FAILURE';

//user update profile
export const POST_UPDATE_PROFILE_REQUEST = 'POST_UPDATE_PROFILE_REQUEST';
export const GET_UPDATE_PROFILE_SUCCESS = 'GET_UPDATE_PROFILE_SUCCESS';
export const GET_UPDATE_PROFILE_FAILURE = 'GET_UPDATE_PROFILE_FAILURE';

//change password
export const POST_CHANGE_PASSWORD_REQUEST = 'POST_CHANGE_PASSWORD_REQUEST';
export const GET_CHANGE_PASSWORD_SUCCESS = 'GET_CHANGE_PASSWORD_SUCCESS';
export const GET_CHANGE_PASSWORD_FAILURE = 'GET_CHANGE_PASSWORD_FAILURE';

//user subscription
export const POST_USER_SUBSCRIPTION_REQUEST = 'POST_USER_SUBSCRIPTION_REQUEST';
export const GET_USER_SUBSCRIPTION_SUCCESS = 'GET_USER_SUBSCRIPTION_SUCCESS';
export const GET_USER_SUBSCRIPTION_FAILURE = 'GET_USER_SUBSCRIPTION_FAILURE';

//---------Link thumbnail Image
export const POST_UPDATE_LINK_THUMBNAIL_IMAGE_REQUEST = 'POST_UPDATE_LINK_THUMBNAIL_IMAGE_REQUEST';
export const GET_UPDATE_LINK_THUMBNAIL_IMAGE_SUCCESS = 'GET_UPDATE_LINK_THUMBNAIL_IMAGE_SUCCESS';
export const GET_UPDATE_LINK_THUMBNAIL_IMAGE_FAILURE = 'GET_UPDATE_LINK_THUMBNAIL_IMAGE_FAILURE';

//------media link
export const POST_MEDIA_CONTENT_REQUEST = 'POST_MEDIA_CONTENT_REQUEST';
export const GET_MEDIA_CONTENT_SUCCESS = 'GET_MEDIA_CONTENT_SUCCESS';
export const GET_MEDIA_CONTENT_FAILURE = 'GET_MEDIA_CONTENT_FAILURE';

//------news letter
export const POST_NEWSLETTER_REQUEST = 'POST_NEWSLETTER_REQUEST';
export const GET_NEWSLETTER_SUCCESS = 'GET_NEWSLETTER_SUCCESS';
export const GET_NEWSLETTER_FAILURE = 'GET_NEWSLETTER_FAILURE';

//------get user media content
export const POST_USER_MEDIA_REQUEST = 'POST_USER_MEDIA_REQUEST';
export const GET_USER_MEDIA_SUCCESS = 'GET_USER_MEDIA_SUCCESS';
export const GET_USER_MEDIA_FAILURE = 'GET_USER_MEDIA_FAILURE';

//------get user media music content
export const POST_USER_MEDIA_MUSIC_REQUEST = 'POST_USER_MEDIA_MUSIC_REQUEST';
export const GET_USER_MEDIA_MUSIC_SUCCESS = 'GET_USER_MEDIA_MUSIC_SUCCESS';
export const GET_USER_MEDIA_MUSIC_FAILURE = 'GET_USER_MEDIA_MUSIC_FAILURE';

//------------profileurl
export const PROFILE_URL = 'PROFILE_URL';

//------get like media music content
export const POST_Like_MEDIA_MUSIC_REQUEST = 'POST_Like_MEDIA_MUSIC_REQUEST';
export const GET_Like_MEDIA_MUSIC_SUCCESS = 'GET_Like_MEDIA_MUSIC_SUCCESS';
export const GET_Like_MEDIA_MUSIC_FAILURE = 'GET_Like_MEDIA_MUSIC_FAILURE';

//------get bookmark media music content
export const POST_BOOKMARK_MEDIA_MUSIC_REQUEST = 'POST_BOOKMARK_MEDIA_MUSIC_REQUEST';
export const GET_BOOKMARK_MEDIA_MUSIC_SUCCESS = 'GET_BOOKMARK_MEDIA_MUSIC_SUCCESS';
export const GET_BOOKMARK_MEDIA_MUSIC_FAILURE = 'GET_BOOKMARK_MEDIA_MUSIC_FAILURE';

//------get all bookmark media music content
export const POST_USER_BOOKMARK_MUSIC_REQUEST = 'POST_USER_BOOKMARK_MUSIC_REQUEST';
export const GET_USER_BOOKMARK_MUSIC_SUCCESS = 'GET_USER_BOOKMARK_MUSIC_SUCCESS';
export const GET_USER_BOOKMARK_MUSIC_FAILURE = 'GET_USER_BOOKMARK_MUSIC_FAILURE';

//----------firebase chat 
// export const SEND_MESSAGE = 'SEND_MESSAGE';
// export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
// export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

// export const RETRIEVE_MESSAGE = 'RETRIEVE_MESSAGE';

// export const POST_MESSAGES_REQUEST = 'POST_MESSAGES_REQUEST';
// export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
// export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';

// export const POST_SEND_MESSAGES_REQUEST = 'POST_SEND_MESSAGES_REQUEST';
// export const GET_SEND_MESSAGES_SUCCESS = 'GET_SEND_MESSAGES_SUCCESS';
// export const GET_SEND_MESSAGES_FAILURE = 'GET_SEND_MESSAGES_FAILURE';

// export const POST_CHAT_LIST_REQUEST = 'POST_CHAT_LIST_REQUEST';
// export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
// export const GET_CHAT_LIST_FAILURE = 'GET_CHAT_LIST_FAILURE';

export const POST_DISABLE_USER_REQUEST = 'POST_DISABLE_USER_REQUEST';
export const GET_DISABLE_USER_SUCCESS = 'GET_DISABLE_USER_SUCCESS';
export const GET_DISABLE_USER_FAILURE = 'GET_DISABLE_USER_FAILURE';

export const POST_CHECK_DISABLE_USER_REQUEST = 'POST_CHECK_DISABLE_USER_REQUEST';
export const GET_CHECK_DISABLE_USER_SUCCESS = 'GET_CHECK_DISABLE_USER_SUCCESS';
export const GET_CHECK_DISABLE_USER_FAILURE = 'GET_CHECK_DISABLE_USER_FAILURE';

export const POST_SUBSCRIPTION_PAYMENT_REQUEST = 'POST_SUBSCRIPTION_PAYMENT_REQUEST';
export const GET_SUBSCRIPTION_PAYMENT_SUCCESS = 'GET_SUBSCRIPTION_PAYMENT_SUCCESS';
export const GET_SUBSCRIPTION_PAYMENT_FAILURE = 'GET_SUBSCRIPTION_PAYMENT_FAILURE';

export const POST_SUBSCRIPTION_EXPIRED_REQUEST = 'POST_SUBSCRIPTION_EXPIRED_REQUEST';
export const GET_SUBSCRIPTION_EXPIRED_SUCCESS = 'GET_SUBSCRIPTION_EXPIRED_SUCCESS';
export const GET_SUBSCRIPTION_EXPIRED_FAILURE = 'GET_SUBSCRIPTION_EXPIRED_FAILURE';

//----------firebase chat 
export const POST_AUDIENCE_DATA_REQUEST = 'POST_AUDIENCE_DATA_REQUEST';
export const GET_AUDIENCE_DATA_SUCCESS = 'GET_AUDIENCE_DATA_SUCCESS';
export const GET_AUDIENCE_DATA_FAILURE = 'GET_AUDIENCE_DATA_FAILURE';

export const POST_CONVERSATION_REQUEST = 'POST_CONVERSATION_REQUEST';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_FAILURE = 'GET_CONVERSATION_FAILURE';

export const POST_MESSAGES_REQUEST = 'POST_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';

export const POST_ADD_CONVERSATION_REQUEST = 'POST_ADD_CONVERSATION_REQUEST';
export const GET_ADD_CONVERSATION_SUCCESS = 'GET_ADD_CONVERSATION_SUCCESS';
export const GET_ADD_CONVERSATION_FAILURE = 'GET_ADD_CONVERSATION_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const POST_GROUP_MESSAGES_REQUEST = 'POST_GROUP_MESSAGES_REQUEST';
export const GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS';
export const GET_GROUP_MESSAGES_FAILURE = 'GET_GROUP_MESSAGES_FAILURE';

export const SEND_GROUP_MESSAGE_REQUEST = 'SEND_GROUP_MESSAGE_REQUEST';
export const SEND_GROUP_MESSAGE_SUCCESS = 'SEND_GROUP_MESSAGE_SUCCESS';
export const SEND_GROUP_MESSAGE_FAILURE = 'SEND_GROUP_MESSAGE_FAILURE';

 // unread message count 
export const UNREAD_MESSAGE_COUNT_REQUEST = 'UNREAD_MESSAGE_COUNT_REQUEST';
export const UNREAD_MESSAGE_COUNT_SUCCESS = 'UNREAD_MESSAGE_COUNT_SUCCESS';
export const UNREAD_MESSAGE_COUNT_FAILURE = 'UNREAD_MESSAGE_COUNT_FAILURE';

export const POST_SUBSCRIBEUSER_STATUS_REQUEST = 'POST_SUBSCRIBEUSER_STATUS_REQUEST';
export const GET_SUBSCRIBEUSER_STATUS_SUCCESS = 'GET_SUBSCRIBEUSER_STATUS_SUCCESS';
export const GET_SUBSCRIBEUSER_STATUS_FAILURE = 'GET_SUBSCRIBEUSER_STATUS_FAILURE';

//For notification
export const LIKED_NOTIFICATION = 'Liked your post';
export const SUBSCRIBED_NOTIFICATION = 'Subscribed';
export const POST_CONTENT = 'Added new post';
export const MESSAGE_NOTIFICATION = 'New message';

//subscriber count
export const  POST_USER_SUBSCRIBEUSER_COUNT_REQUEST = 'POST_USER_SUBSCRIBEUSER_COUNT_REQUEST';
export const  GET_USER_SUBSCRIBEUSER_COUNT_SUCCESS = 'GET_USER_SUBSCRIBEUSER_COUNT_SUCCESS';
export const  GET_USER_SUBSCRIBEUSER_COUNT_FAILURE = 'GET_USER_SUBSCRIBEUSER_COUNT_FAILURE';

//get user notification
export const  POST_USER_NOTIFICATION_REQUEST = 'POST_USER_NOTIFICATION_REQUEST';
export const  GET_USER_NOTIFICATION_SUCCESS = 'GET_USER_NOTIFICATION_SUCCESS';
export const  GET_USER_NOTIFICATION_FAILURE = 'GET_USER_NOTIFICATION_FAILURE';

 // unread notification count 
 export const UNREAD_NOTIFICATION_COUNT_REQUEST = 'UNREAD_NOTIFICATION_COUNT_REQUEST';
 export const UNREAD_NOTIFICATION_COUNT_SUCCESS = 'UNREAD_NOTIFICATION_COUNT_SUCCESS';
 export const UNREAD_NOTIFICATION_COUNT_FAILURE = 'UNREAD_NOTIFICATION_COUNT_FAILURE';


 // Remove notification 
 export const REMOVE_NOTIFICATION_REQUEST = 'REMOVE_NOTIFICATION_REQUEST';
 export const REMOVE_NOTIFICATION_SUCCESS = 'REMOVE_NOTIFICATION_SUCCESS';
 export const REMOVE_NOTIFICATION_FAILURE = 'REMOVE_NOTIFICATION_FAILURE';

 //------get share media music content
export const POST_SHARE_MEDIA_MUSIC_REQUEST = 'POST_SHARE_MEDIA_MUSIC_REQUEST';
export const GET_SHARE_MEDIA_MUSIC_SUCCESS = 'GET_SHARE_MEDIA_MUSIC_SUCCESS';
export const GET_SHARE_MEDIA_MUSIC_FAILURE = 'GET_SHARE_MEDIA_MUSIC_FAILURE';

//------instagram insights user
export const POST_USER_INSTAGRAM_INSIGHTS_REQUEST = 'POST_USER_INSTAGRAM_INSIGHTS_REQUEST';
export const GET_USER_INSTAGRAM_INSIGHTS_SUCCESS = 'GET_USER_INSTAGRAM_INSIGHTS_SUCCESS';
export const GET_USER_INSTAGRAM_INSIGHTS_FAILURE = 'GET_USER_INSTAGRAM_INSIGHTS_FAILURE';

export const POST_USER_INSTAGRAM_INSIGHTS_POST_REQUEST =  'POST_USER_INSTAGRAM_INSIGHTS_POST_REQUEST';
export const GET_USER_INSTAGRAM_INSIGHTS_POST_FAILURE =  'GET_USER_INSTAGRAM_INSIGHTS_POST_FAILURE';
export const GET_USER_INSTAGRAM_INSIGHTS_POST_SUCCESS =  'GET_USER_INSTAGRAM_INSIGHTS_POST_SUCCESS';

export const POST_INSTAGRAM_TOP_CITY_AUDIENCE_REQUEST =  'POST_INSTAGRAM_TOP_CITY_AUDIENCE_REQUEST';
export const GET_INSTAGRAM_TOP_CITY_AUDIENCE_FAILURE =  'GET_INSTAGRAM_TOP_CITY_AUDIENCE_FAILURE';
export const GET_INSTAGRAM_TOP_CITY_AUDIENCE_SUCCESS =  'GET_INSTAGRAM_TOP_CITY_AUDIENCE_SUCCESS';


export const POST_INSTAGRAM_FOLLOWERS_REQUEST =  'POST_INSTAGRAM_FOLLOWERS_REQUEST';
export const GET_INSTAGRAM_FOLLOWERS_FAILURE =  'GET_INSTAGRAM_FOLLOWERS_FAILURE';
export const GET_INSTAGRAM_FOLLOWERS_SUCCESS =  'GET_INSTAGRAM_FOLLOWERS_SUCCESS';

export const POST_INSTAGRAM_FOLLOWER_GROWTH_REQUEST = 'POST_INSTAGRAM_FOLLOWER_GROWTH_REQUEST';
export const GET_INSTAGRAM_FOLLOWER_GROWTH_FAILURE = 'GET_INSTAGRAM_FOLLOWER_GROWTH_FAILURE';
export const GET_INSTAGRAM_FOLLOWER_GROWTH_SUCCESS = 'GET_INSTAGRAM_FOLLOWER_GROWTH_SUCCESS';


export const POST_CREATE_STRIPE_ACCOUNT_REQUEST = 'POST_CREATE_STRIPE_ACCOUNT_REQUEST';
export const GET_CREATE_STRIPE_ACCOUNT_FAILURE = 'GET_CREATE_STRIPE_ACCOUNT_FAILURE';
export const GET_CREATE_STRIPE_ACCOUNT_SUCCESS = 'GET_CREATE_STRIPE_ACCOUNT_SUCCESS';


export const POST_USER_STRIPE_ACCOUNT_DETAILS_REQUEST = 'POST_USER_STRIPE_ACCOUNT_DETAILS_REQUEST';
export const GET_USER_STRIPE_ACCOUNT_DETAILS_FAILURE = 'GET_USER_STRIPE_ACCOUNT_DETAILS_FAILURE';
export const GET_USER_STRIPE_ACCOUNT_DETAILS_SUCCESS = 'GET_USER_STRIPE_ACCOUNT_DETAILS_SUCCESS';

export const POST_USER_STRIPE_ACCOUNT_LOGIN_LINKS_REQUEST = 'POST_USER_STRIPE_ACCOUNT_LOGIN_LINKS_REQUEST';
export const GET_USER_STRIPE_ACCOUNT_LOGIN_LINKS_FAILURE = 'GET_USER_STRIPE_ACCOUNT_LOGIN_LINKS_FAILURE';
export const GET_USER_STRIPE_ACCOUNT_LOGIN_LINKS_SUCCESS = 'GET_USER_STRIPE_ACCOUNT_LOGIN_LINKS_SUCCESS';

export const POST_USER_PAYOUT_REQUEST = 'POST_USER_PAYOUT_REQUEST';
export const GET_USER_PAYOUT_SUCCESS = 'GET_USER_PAYOUT_SUCCESS';
export const GET_USER_PAYOUT_FAILURE = 'GET_USER_PAYOUT_FAILURE';

export const POST_MEDIA_SHARE_COUNT_REQUEST = 'POST_MEDIA_SHARE_COUNT_REQUEST';
export const ADD_MEDIA_SHARE_COUNT_SUCCESS = 'ADD_MEDIA_SHARE_COUNT_SUCCESS';
export const ADD_MEDIA_SHARE_COUNT_FAILURE = 'ADD_MEDIA_SHARE_COUNT_FAILURE';

export const GET_USER_MEDIA_SHARE_COUNT_REQUEST = 'GET_USER_MEDIA_SHARE_COUNT_REQUEST';
export const GET_USER_MEDIA_SHARE_COUNT_SUCCESS = 'GET_USER_MEDIA_SHARE_COUNT_SUCCESS';
export const GET_USER_MEDIA_SHARE_COUNT_FAILURE = 'GET_USER_MEDIA_SHARE_COUNT_FAILURE';

